knp_snappy:
    pdf:
        enabled:    true
        binary:     "\"O:\\wamp64\\www\\CDA\\Fil_rouge\\Symfony_fil_rouge\\ressources\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
        options:    []
    image:
        enabled:    true
        binary:     "\"O:\\wamp64\\www\\CDA\\Fil_rouge\\Symfony_fil_rouge\\ressources\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\"" 
        options:    []