knp_snappy:
    pdf:
        enabled:    true
        binary:     "\"C:\\Users\\Océane\\AppData\\Local\\Temp\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
        options:    []
    image:
        enabled:    true
        binary:     "\"C:\\Users\\Océane\\AppData\\Local\\Temp\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\"" 
        options:    []